### ISSUE TITLE
Refinement: make sure 2 automata have the same alphabet (inputs, outputs)

### ISSUE THREAD

**Issue by trinnguyen** [uniba-swt/ia-toolset#2]
## Requirements
- In refinement pre-order, implementation and specification must have the same inputs and outputs, no more no less.
- Below example should result **invalid refinement** (even there is alternating simulation relationship at the init state)
```
actions { a, b }
proc P {
  act { a? }
  a?
}
proc Q {
  act { a?, b! }
  a?
}
init {
 refinement(P(), Q()) 
}
```

## Files to look at:
- IAM: `MemBesRefinementOperation`
- MIA: `ModalBesRefinement`
- `AbstractBesRefinementOperation`

**Comment by eyip002** [comment]
Does this requirement apply to IA?

Reference: Luca de Alfaro and Thomas A. Henzinger. 2001. Interface automata. SIGSOFT Softw. Eng. Notes 26, 5 (Sept. 2001), 109–120. DOI: https://doi.org/10.1145/503271.503226

The definition of refinement does not require the input and output actions of P to be identical to Q:
<img width="1116" alt="Screen Shot 2021-07-16 at 13 11 50" src="https://user-images.githubusercontent.com/7035180/125939191-e1f0e056-566a-4dd5-bac2-8e89d2b9271d.png">

Note that P in the definition is a specification while Q is an implementation.

**Comment by trinnguyen** [comment]
This is the current implementation, which does not require the alphabets to be exactly the same.

And also for the published paper of Interface Automata for Shared Memory (2019) below, there is no additional constraint on the alphabets:

Gareis, J., Lüttgen, G., Schinko, A., Vogler, W., 2019. Interface Automata for Shared Memory - Springer, in: Margaria, T., Graf, S., Larsen, K.G. (Eds.), Models, Mindsets, Meta: The What, the How, and the Why Not? Essays Dedicated to Bernhard Steffen on the Occasion of His 60th Birthday, Lecture Notes in Computer Science. Springer International Publishing, Cham, pp. 151–166. https://doi.org/10.1007/978-3-030-22348-9_10

**However, in our latest draft journal, both automata must have the same signature.**

**Comment by trinnguyen** [comment]
Oh, if we implement another dialect for IA only, then this shouldn't be applied. Note that for IA, use below version instead: (the one published in 2005 instead of 2001)

de Alfaro, L., Henzinger, T.A., 2005. Interface-Based Design, in: Broy, M., Grünbauer, J., Harel, D., Hoare, T. (Eds.), Engineering Theories of Software Intensive Systems, NATO Science Series. Springer Netherlands, Dordrecht, pp. 83–104. https://doi.org/10.1007/1-4020-3532-2_3

Currently, IA is indirect supported via IAM, so even with the IA model that has no shared variable, we should still follow IAM semantics (same signature in refinement).

**Comment by eyip002** [comment]
See Definitions 5 and 8 in https://link.springer.com/article/10.1007/s00236-021-00408-8

> Definition 5 
> (Alternating Simulation) For IAs P, Q with the **same signature** ...

> Definition 8
> (Alternating Simulation) For IAMs P and Q with the **same signature** ...

**Comment by eyip002** [comment]
Fixed in
